---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-job-cleaner
  namespace: kube-job-cleaner
  labels:
    application: kube-job-cleaner
    version: "0.9"
spec:
  schedule: "17 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            application: kube-job-cleaner
            version: "0.9"
        spec:
          serviceAccountName: kube-job-cleaner
          restartPolicy: OnFailure
          containers:
            - name: cleaner
              image: "frauniki/kube-job-cleaner:latest"
              args:
                - --ignore-namespaces $IGNORE_NAMESPACES
              env:
                - name: IGNORE_NAMESPACES
                  valueFrom:
                    configMapKeyRef:
                      name: kube-job-cleaner
                      key: IGNORE_NAMESPACES
              resources:
                limits:
                  cpu: "2"
                  memory: 2Gi
                requests:
                  cpu: 500m
                  memory: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-job-cleaner
  namespace: kube-job-cleaner
data:
  IGNORE_NAMESPACES: ""
